skip-check:
  # Skipping specific Checkov checks if you need exceptions
  - CKV_AWS_79  # Example: Skip 'Ensure EC2 instances are managed by Auto Scaling Groups'
  - CKV_AWS_116 # Skip 'Ensure that detailed monitoring is enabled for EC2 instances'
