name: Execute Terraform

on:
  workflow_dispatch:
    inputs:
      aws_region:
        description: "AWS Region"
        required: true
      ami_id:
        description: "AMI ID for the EC2 instance"
        required: true
      instance_type:
        description: "Type of EC2 instance"
        required: true

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Configure AWS Credentials
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ github.event.inputs.aws_region }}

      # Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6

      # Initialize Terraform
      - name: Terraform Init
        run: terraform init

      # Plan Terraform
      - name: Terraform Plan
        run: terraform plan -var="aws_region=${{ github.event.inputs.aws_region }}" -var="ami_id=${{ github.event.inputs.ami_id }}" -var="instance_type=${{ github.event.inputs.instance_type }}"

      # Apply Terraform
      - name: Terraform Apply
        run: terraform apply -auto-approve -var="aws_region=${{ github.event.inputs.aws_region }}" -var="ami_id=${{ github.event.inputs.ami_id }}" -var="instance_type=${{ github.event.inputs.instance_type }}"
