name: Retrieve Secret from Vault using JWT Auth

on:
  push:
    branches:
      - master

jobs:
  get-secret:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for JWT auth
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Authenticate to Vault using JWT
        uses: hashicorp/vault-action@v2
        with:
          url: http://http://127.0.0.1:8200  # Your Vault URL
          method: jwt
          role: github-actions  # Vault role configured for JWT
          jwtGithubAudience: vault.example.com  # Audience configured in Vault

      - name: Retrieve secret from Vault
        run: |
          vault kv get -format=json secret/my-secret | jq -r '.data.data.token' > token.txt

      - name: Use secret token
        run: |
          TOKEN=$(cat token.txt)
          echo "The retrieved token is: $TOKEN"
