name: Setup Vault, Configure Policy and Role, Retrieve Secret

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read

jobs:
  setup-and-fetch-secret:
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download and Install Vault
        run: |
          curl -fsSL https://releases.hashicorp.com/vault/1.15.4/vault_1.15.4_linux_amd64.zip -o vault.zip
          unzip vault.zip
          sudo mv vault /usr/local/bin/
          vault --version

      - name: Start Vault Dev Server
        run: |
          vault server -dev -dev-root-token-id="root" &
          sleep 5
          export VAULT_ADDR='http://127.0.0.1:8200'
          export VAULT_TOKEN='root'
          echo "VAULT_ADDR=$VAULT_ADDR" >> $GITHUB_ENV
          echo "VAULT_TOKEN=$VAULT_TOKEN" >> $GITHUB_ENV

      - name: Configure Vault Policy, Role, and Secret
        run: |
          vault secrets enable -version=2 kv
          vault kv put secret/my-secret my-value="HelloWorld"

          echo 'path "secret/data/my-secret" { capabilities = ["read"] }' > my-policy.hcl
          vault policy write my-policy my-policy.hcl

          vault auth enable -path=github-jwt jwt
          vault write auth/github-jwt/config oidc_discovery_url="https://token.actions.githubusercontent.com" bound_issuer="https://token.actions.githubusercontent.com"

          cat <<EOF > role.json
          {
            "role_type": "jwt",
            "bound_audiences": "https://github.com/toharikr",
            "user_claim": "repository",
            "bound_claims": {
              "environment": "dev",
              "repository": "toharikr/Hello"
            },
            "policies": "my-policy",
            "ttl": "1h"
          }
          EOF

          vault write auth/github-jwt/role/my-role @role.json

      - name: valur secret list
        run: |
            vault secrets list

      - name: Import Secrets from HashiCorp Vault using JWT
        uses: hashicorp/vault-action@v3
        with:
          url: ${{ env.VAULT_ADDR }}
          method: jwt
          path: github-jwt
          role: my-role
          secrets: |
            secret/data/my-secret my-value | MY_SECRET

      - name: Use the secret
        run: |
          echo "$(echo -n ${{env.MY_SECRET}} | base64)"

