name: Retrieve Secret from Vault using JWT Auth

on:
  push:
    branches:
      - master

jobs:
  get-secret:
    runs-on: ubuntu-latest

    permissions:
      id-token: write  # Required for JWT auth
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Import Secrets from HashiCorp Vault
        uses: hashicorp/vault-action@v3
        with:
          url: http://127.0.0.1:8200
          token: ${{ secrets.VAULT_SECRET }}
          secrets: |
            secret/data/my-secret MY_SECRET | MY_SECRET

      - name: Use the secret
        run: |
          echo "The secret value is: $MY_SECRET"
